# Generated by Django 5.0.3 on 2024-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('note', models.TextField(max_length=200)),
            ],
        ),
    ]
