# Generated by Django 5.0.3 on 2024-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
