# Generated by Django 5.0.3 on 2024-03-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_outcome_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(),
        ),
    ]
