# Generated by Django 5.0.3 on 2024-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_outcome_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
