# Generated by Django 5.0.3 on 2024-03-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_outcome_date'),
        ('dashboard', '0004_alter_outcome_id'),
    ]

    operations = [
    ]
